version: '3'

services:
  frontend_service: 
    build: ./frontend-example-docker-master
    environment:
      - API_URL=http://localhost:8000
    ports:
      - "5000:5000" 
    
  
  backend_service:
    build: ./backend-example-docker-master
    environment:
      - FRONT_URL=http://localhost:5000
    ports:
      - "8000:8000"

