version: '3'

services:
  frontend_service: 
    build: ./frontend-example-docker-master
    environment:
      - API_URL=http://localhost:8000
    ports:
      - "5000:5000" 
    
  backend_service:
    build: ./backend-example-docker-master
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis_service
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres_service
      - DB_NAME=postgres
    ports:
      - "8000:8000"
    depends_on:
      - redis_service
      - postgres_service
    links:
      - redis_service
      - postgres_service

  redis_service: 
    image: redis:latest
    ports:
      - "6379:6379"
      
  postgres_service: 
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx_service:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend_service
      - backend_service
  
