version: '3'

services:
  frontend_service: 
    build: ./ml-kurkkumopo-frontend
    ports:
      - "3000:3000" 
    
  backend_service:
    build: ./ml-kurkkumopo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./model:/src/model
      
  training_service: 
    build: ./ml-kurkkumopo-training
    volumes:
      - ./model:/src/model
      - ./imgs:/src/imgs

