version: '3'

services:
  frontend_service: 
    build: ./frontend-example-docker-master
    environment:
      - API_URL=http://localhost:8000
    ports:
      - "5000:5000" 
    
  backend_service:
    build: ./backend-example-docker-master
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis_service
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - redis_service
    links:
      - redis_service

  redis_service: 
    image: redis:latest
    ports:
      - "6379:6379"
